# Generated by Django 3.2.16 on 2022-11-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0002_alter_subdivisao_sub_divisao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='matricula_escolar',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='whatsapp2',
        ),
        migrations.AlterField(
            model_name='atleta',
            name='altura',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='peso',
            field=models.CharField(max_length=5),
        ),
    ]
