# Generated by Django 3.2.16 on 2022-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0003_auto_20221117_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='camisa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='perna_dominante',
            field=models.CharField(choices=[('D', 'Direita'), ('E', 'Esquerda'), ('A', 'Ambidestro')], max_length=1),
        ),
    ]
