# Generated by Django 3.2.16 on 2022-11-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0004_auto_20221117_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='camisa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
