# Generated by Django 3.2.16 on 2022-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0005_alter_atleta_camisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='imagem_modalidade',
            field=models.ImageField(blank=True, null=True, upload_to='FotosModalidades'),
        ),
    ]
