# Generated by Django 3.2.16 on 2022-11-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0007_jogos'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='descricao_jogo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
