# Generated by Django 3.2.16 on 2022-11-11 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0003_rename_data_de_criacao_usuario_data_de_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('contato_emergencia', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('foto_cpf', models.FileField(upload_to='funcionario/cpf')),
                ('rg', models.CharField(max_length=12, unique=True)),
                ('foto_rg', models.FileField(upload_to='funcionario/rg')),
                ('funcao', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=5)),
                ('horario_de_trabalho', models.DecimalField(decimal_places=2, max_digits=20)),
                ('admitido', models.DateTimeField(default=datetime.datetime.now)),
                ('foto_funcionario', models.FileField(blank=True, upload_to='FotoFuncionario')),
                ('ativo', models.BooleanField(default=True)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=100)),
                ('conta', models.CharField(max_length=100)),
                ('pix', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"facilitis"."funcionario"',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_local', models.CharField(max_length=30)),
            ],
            options={
                'db_table': '"facilitis"."local"',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_da_ocorrencia', models.CharField(max_length=100)),
                ('descricao_da_ocorrencia', models.TextField()),
                ('status', models.CharField(choices=[('ABT', 'Aberto'), ('EA', 'Em Andamento'), ('C', 'Concluido')], max_length=3)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facilitis.local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
            options={
                'db_table': '"facilitis"."ocorrencia"',
            },
        ),
    ]
