# Generated by Django 3.2.16 on 2022-11-13 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='data_de_criacao',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
