# Generated by Django 3.2.16 on 2022-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ocorrencias', '0002_ocorrencia_data_de_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_de_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
