# Generated by Django 3.2.16 on 2022-11-12 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('contato_emergencia', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('foto_cpf', models.FileField(upload_to='funcionario/cpf')),
                ('rg', models.CharField(max_length=12, unique=True)),
                ('foto_rg', models.FileField(upload_to='funcionario/rg')),
                ('funcao', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=5)),
                ('horario_de_trabalho', models.DecimalField(decimal_places=2, max_digits=20)),
                ('admitido', models.DateTimeField(default=datetime.datetime.now)),
                ('foto_funcionario', models.FileField(blank=True, upload_to='FotoFuncionario')),
                ('ativo', models.BooleanField(default=True)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=100)),
                ('conta', models.CharField(max_length=100)),
                ('pix', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"facilitis"."funcionario"',
            },
        ),
    ]
