# Generated by Django 3.2.16 on 2022-11-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
