# Generated by Django 3.2.16 on 2022-11-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0002_alter_funcionario_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='horario_de_trabalho',
            field=models.CharField(max_length=2),
        ),
    ]
