# Generated by Django 3.2.16 on 2022-11-11 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelDeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=3)),
                ('descricao_do_nivel', models.CharField(max_length=30)),
            ],
            options={
                'db_table': '"usuario"."nivel_de_usuario"',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('nascimento', models.DateField()),
                ('foto_de_perfil', models.ImageField(blank=True, upload_to='FotosPerfil')),
                ('nivel_de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.niveldeusuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"usuario"."usuario"',
            },
        ),
    ]
