# Generated by Django 3.2.16 on 2022-11-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20221111_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='data_de_criacao',
            new_name='data_de_registro',
        ),
    ]
