# Generated by Django 3.2.16 on 2022-11-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Atletas', '0005_alter_atleta_camisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atletas.atleta')),
            ],
            options={
                'db_table': '"consultas"."consulta"',
            },
        ),
        migrations.CreateModel(
            name='EstruturaLesionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrutura_lesionada', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"consultas"."estruturalesionada"',
            },
        ),
        migrations.CreateModel(
            name='ExamesComplementares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_exame', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"consultas"."examecomplementares"',
            },
        ),
        migrations.CreateModel(
            name='RegiaoDoCorpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte_do_corpo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"consultas"."regiodocorpo"',
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('justificativa', models.TextField()),
                ('imagem_exame', models.ImageField(blank=True, null=True, upload_to='')),
                ('justificativa_complementares', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.consulta')),
                ('exame_complementar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.examescomplementares')),
            ],
            options={
                'db_table': '"consultas"."tratamento"',
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('justificativa', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.consulta')),
            ],
            options={
                'db_table': '"consultas"."saida"',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo_manutencao', models.CharField(choices=[('R', 'Recovery'), ('A', 'Analgesia'), ('O', 'Terapia Manual Osteopatia'), ('M', 'Terapia Manual Manipulação')], max_length=1)),
                ('justificativa', models.CharField(max_length=100)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.consulta')),
            ],
            options={
                'db_table': '"consultas"."manutencao"',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('observacao', models.CharField(max_length=100)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.consulta')),
                ('estrutura_lesionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.estruturalesionada')),
                ('regiao_corpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.regiaodocorpo')),
            ],
            options={
                'db_table': '"consultas"."entrada"',
            },
        ),
    ]
