# Generated by Django 3.2.16 on 2022-11-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='observacao',
            field=models.TextField(),
        ),
    ]
