# Generated by Django 3.2.16 on 2022-11-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultas', '0002_alter_entrada_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exametratamento',
            name='imagem_exame',
            field=models.ImageField(blank=True, null=True, upload_to='FotoExames'),
        ),
    ]
