# Generated by Django 3.2.16 on 2022-12-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0008_jogos_descricao_jogo'),
        ('Consultas', '0004_alter_manutencao_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='atleta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Atletas.atleta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exametratamento',
            name='atleta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Atletas.atleta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manutencao',
            name='atleta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Atletas.atleta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saida',
            name='atleta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Atletas.atleta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamento',
            name='atleta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Atletas.atleta'),
            preserve_default=False,
        ),
    ]
